// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJw76L1IJufZI_5AW9au8NHTJezp3iVU',
    appId: '1:386624962173:web:14288ba9ee7efa85b2fb14',
    messagingSenderId: '386624962173',
    projectId: 'aura-b548b',
    authDomain: 'aura-b548b.firebaseapp.com',
    storageBucket: 'aura-b548b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOCAkv36gznkhs9PkpIKLHJsIOfE6NUs',
    appId: '1:386624962173:android:d44e959e05eb8475b2fb14',
    messagingSenderId: '386624962173',
    projectId: 'aura-b548b',
    storageBucket: 'aura-b548b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7v5pWgbQvwE9IVwaCTG5WPboZXQEQOC0',
    appId: '1:386624962173:ios:0920fb82e4f56aa6b2fb14',
    messagingSenderId: '386624962173',
    projectId: 'aura-b548b',
    storageBucket: 'aura-b548b.firebasestorage.app',
    iosBundleId: 'com.junhyuk.aura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7v5pWgbQvwE9IVwaCTG5WPboZXQEQOC0',
    appId: '1:386624962173:ios:0920fb82e4f56aa6b2fb14',
    messagingSenderId: '386624962173',
    projectId: 'aura-b548b',
    storageBucket: 'aura-b548b.firebasestorage.app',
    iosBundleId: 'com.junhyuk.aura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJw76L1IJufZI_5AW9au8NHTJezp3iVU',
    appId: '1:386624962173:web:ada34b5523e6dc0cb2fb14',
    messagingSenderId: '386624962173',
    projectId: 'aura-b548b',
    authDomain: 'aura-b548b.firebaseapp.com',
    storageBucket: 'aura-b548b.firebasestorage.app',
  );

}